### ISSUE TITLE
watchId Result

### ISSUE THREAD

**Issue by jdmadriz** [RadiusNetworks/hello-proximity-cordova#5]
Hi I implemented the hello-proximity app and everything looks to work find but, I put and alert to the watchId result and I'm getting random UUID identifiers I do create my ProximityKit.plist file with my beacon UUID and the same happened I also complete removed the PtoximityKit.plist file from the project and the watchId continue returning random UUID's, any ideas what I could be doing wrong please.

**Comment by jdmadriz** [comment]
Can someone help me with this issue please!!!q

**Comment by jdmadriz** [comment]
Any Help please!!!

**Comment by jnebeker** [comment]
`watchId` is an internal identifier that is returned by the `watchProximity`.  This is used to identify this particular instance of `watchProximity` so that you can stop receiving callbacks from Proximity Kit (if desired) with a call to `clearWatch` (that takes this `watchId` as a parameter).  Therefore, `watchId` isn't related to the UUID that is associated with beacon identifiers and Proximity Kit.  It is just a random identifier used to keep track of Proximity Kit callbacks.  Here is a link with more info on the Proximity Kit cordova plugin and its usage:

https://github.com/RadiusNetworks/proximitykit-plugin-cordova#usage

**Comment by jdmadriz** [comment]
Ok jnebeker I understand better now, so how can I get the UUID of my nearby beacon?

**Comment by jnebeker** [comment]
In the javascript when you receive a Proximity Kit event callback from `watchProximity` it will send a `message` object to the success handler function that you've designated to receive the callback.  You can filter the event types of these message objects for `didRangeBeacon` events, which contain additional data about the beacon (including UUID).  Here's some more info about the beacon data structure in the message object:

https://github.com/RadiusNetworks/proximitykit-plugin-cordova#beacon-data

And here's the example success handler function from the reference app that receives these events in the form of message objects.  

https://github.com/RadiusNetworks/hello-proximity-cordova/blob/validate_instructions/www/js/index.js#L54
